services:
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - '5001:5000'
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://user:password@database:5432/notifications
      - REDIS_URL=redis://redis:6379
      - FRONTEND_URL=http://frontend:3000
    depends_on:
      - database
      - redis

  database:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: notifications
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

  redis:
    image: redis
    ports:
      - '6379:6379'

  nginx:
    image: nginx
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend

